export const SITE = {
  website: "https://blog.jsl.xyz/",
  author: "JSL",
  profile: "https://github.com/jsl9208",
  desc: "Shilong's Tech — AI Agent, AI Infra, Enterprise AI/ML platforms, big data & analytics community",
  title: "Shilong's Tech",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 8,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "",
    url: "",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Asia/Shanghai",
} as const;

export const GISCUS = {
  repo: "jsl9208/blog" as const,
  repoId: "R_kgDORFOq6g",
  category: "General",
  categoryId: "DIC_kwDORFOq6s4C1tFb",
  mapping: "specific" as const,
  reactionsEnabled: true,
  inputPosition: "bottom" as const,
  lightTheme: "/giscus-light.css",
  darkTheme: "/giscus-dark.css",
} as const;
